.editorconfig

See [PEP8](https://www.python.org/dev/peps/pep-0008/) for more.

Conventional coding-style settings for Python

---

README.md

Provides links to the official install docs for pip, virtualenv and nodejs.
Provides instructions on setting up a virtualenv such that the make targets work.

Document how to install the requirements.

---

Makefile
README.md
scripts/elastic_search/mod.py
src/server.py

This commit has been created so that we can make indexes to AWS ES service. 
Features:
- Pulled out the index name into variable in Makefile. Allows us to specify Index name. 
- Using AWSES python module for helping with ES connection
Known issue:
- When running will throw errors for insecure https connection. This will have to be resolved sometime in the future. 
Testing: 
- I was able to get SGD data indexed into the ElasticSearch index. Ran out of memory for uploading the rest.

Aws es services

---

README.md

Added more documentation to README.md to address  #88

Documentation added to README.md 

---

Makefile
scripts/elastic_search/fly.py
scripts/elastic_search/mod.py
scripts/elastic_search/rat.py
scripts/elastic_search/worm.py

Just trying to get the pipeline flow worked out.

Added some extra logging for which files are getting loaded and saved

---

scripts/elastic_search/fetch_and_save.py
scripts/elastic_search/loaders/so_loader.py

Load so data

---

Makefile
requirements.txt
scripts/elastic_search/fetch_and_save.py
scripts/elastic_search/fetch_save_index.py
scripts/elastic_search/loaders/homolog_loader.py
scripts/elastic_search/loaders/so_loader.py
src/server.py

Added Flask-HTTPAuth module
Uploaded homology data to S3 and using that file
Fixed bug in SO Loader for name field
Fixes #112 
This does not include code to make PUT/POST/DELETE work. It only secures the endpoint itself with a password, username is ignored. Username can be used later on once we get a full stack implemented.

Add authentication for Modify Endpoints

---

Makefile
test/integration_tests/test_search.py
test/unit_tests/test_search.py

Added fixes for es import paths for "make tests"

---

scripts/elastic_search/mods/fly.py

Added JSON parsing for Fly data.

---

scripts/elastic_search/mods/zfin.py

use the latest data file on S3.

modifies the latest ZFIN data file name

---

local.env
scripts/elastic_search/loaders/gene_loader.py

Fixes #100, just needed symbol to be indexed as name_key in ES.
I also added a local.env to source so that we can run tests locally without errors from missing ENV variables, which is totally not related to #100 and I just snuck it in hoping that you won't notice and pull the request anyway.   
Will I get away with it?  Only time will tell!

Feature restore gene autocomplete

---

scripts/elastic_search/fetch_and_save.py
scripts/elastic_search/fetch_save_index.py
scripts/elastic_search/mods/__init__.py
scripts/elastic_search/mods/human.py

Loading RGD JSON for human genes.

---

src/js_src/containers/genePage/jbrowse.js

No issue for this one. Just a quick fix for something I noticed.

Update JBrowse track names

---

scripts/elastic_search/loaders/go_gene_annot_loader.py

Adding Sierra's changes for #159

---

scripts/elastic_search/loaders/go_gene_annot_loader.py

Reverts alliance-genome/agr#166
Forgot to ask Sierra if the tests were successful. Whoops.

Revert "Adding Sierra's changes for #159"

---

scripts/elastic_search/loaders/go_gene_annot_loader.py

@sierra-moxon Whenever you've had the chance to test this locally, we can merge (or if it worked earlier today from your other branch).

Adding Sierra's changes for fixing #159

---

README.md
scripts/elastic_search/mods/zfin.py

Removes the ENSDARP records from the gene page (ZFIN).

fixes #175

---

scripts/elastic_search/mods/human.py

Added Human GO data.

---

scripts/elastic_search/mapping.py
src/js_src/containers/search/resultsList.js
src/js_src/containers/search/resultsTable.js
src/js_src/reducers/searchParsers.js
src/services/search_service.py
test/integration_tests/test_search.py

Fix gene_type in search results (renamed to Biotype)

---

scripts/elastic_search/fetch_and_save.py
scripts/elastic_search/fetch_save_index.py
scripts/elastic_search/load_and_index.py

Closes #161. 
The UI still shows some disease-related text.

Temporarily removed disease parsing and loading.

---

src/js_src/constants.js
src/js_src/containers/search/multiTable.js

Removed / hid Disease category from search interface

---

src/js_src/components/orthology/index.js

alliance-genome/agr#152
Hi there, only hard coded example data is changed in this PR. I don't think a review is necessary really, but just have a PR in case. Thanks.

change hard coded gene link to agr link

---

src/dao/elasticsearch_dao.py

This might still need to be tweaked going forward.

Increaced ES timeout for larger queries. Fixes #171

---

src/services/helpers/search_helper.py
src/services/search_service.py

Since id searching was a regression (broke in the conversion to BGI schema in ES) and nearby, I fixed it also.  
Fixes #198 
Fixes #197

Exact symbol matches & id searching

---

scripts/elastic_search/loaders/gene_loader.py

* Please assign a reviewer if this request needs to be reviewed.

passing the right key to the genes dictionary

---

scripts/elastic_search/mods/zfin.py

Took off the URL encoding. Need to re-index (and download the latest BGI version)

fixes #206

---

src/js_src/containers/genePage/basicGeneInfo.js

Trying this PR again since the last one got stuck in CI after a required merge.

Include geneSynopsisUrl in Description field. Fixes #218

---

src/js_src/containers/genePage/dataSourceCard.js

This is a workaround to fix  issue #207  while waiting 
for a permanent solution from the backend groups

Frontend workaround to fix Human gene broken links  in 0.3.0 

---

development.env
docker-compose.yml

This PR updates the Docker container to ES v5 and adds environment variables that were added since I first set this up (#202).  I was able to spin up a clean docker instance, run the database load/index, and perform searches in the webapp using the local ES server.  All tests pass.

Updated Docker configuration for ES 5 and env variables.

---

.travis.yml
Makefile
requirements.txt
scripts/elastic_search/loaders/aggregate_loader.py
src/js_src/containers/genePage/basicGeneInfo.js
src/js_src/containers/search/resultsList.js
src/server.py
test/functional_tests/browser.py
test/functional_tests/environment.py
test/functional_tests/gene_page.feature
test/functional_tests/search_page.feature
test/functional_tests/steps/test_gene_page.py
test/functional_tests/steps/test_search_page.py
test/integration_tests/test_search.py

Adds indexing into to ES to the travis build, brings in the behave python testing framework as well as selenium webdriver to connect, render the page and confirm that at least a small token bit of data is present. 
This bumps the travis build time to 13 minutes, and obviously as we load more data would go up.  Once the time is unacceptable, we should look at a way to truncate loads so that we're bringing in a subset of the data from each source. 
@christabone I added you as a review since I'm hoping this will be helpful to you as you refactor the load - feel free to remove yourself if you're buried in that refactoring work
Fixes #243

Feature functional tests

---

scripts/elastic_search/loaders/gene_loader.py
scripts/elastic_search/mapping/mapping_schema.py

This fixes #245 and removes some older unused chromosome location code from the prototype.
Related JIRA -- http://jira.alliancegenome.org/browse/AGR-260

AGR-260 Fixed genomeLocation bug.

---

indexer/src/loaders/aggregate_loader.py
indexer/src/mapping/es_mapping.py

A quick fix to a blocking bug on the dev.alliancegenome.org server.

Fixed blocking chunk size value.

---

api/test/functional_tests/gene_page.feature
api/test/functional_tests/search_page.feature
indexer/src/annotators/do_annotator.py
indexer/src/loaders/aggregate_loader.py
indexer/src/loaders/disease_loader.py
indexer/src/loaders/do_loader.py
indexer/src/loaders/go_loader.py
indexer/src/loaders/test_check.py
indexer/src/mapping/es_mapping.py
indexer/src/mapping/mapping_schema.py
indexer/src/mods/mouse.py
indexer/src/mods/rat.py
indexer/src/mods/sgd.py
indexer/src/mods/worm.py
indexer/src/mods/zfin.py

changes to get disease ontology loader working, add disease names to the disease terms, commented out the indexing of disease terms because of character encoding issues.

Agr 356 id resolution

---

indexer/src/files/csv_file.py
indexer/src/files/json_file.py

just making sure the utf8 change was applied correctly to json file opener and csv file opener

fixing case sensitivity on file open

---

indexer/src/annotators/do_annotator.py
indexer/src/loaders/do_loader.py

This restores the do_name field which was accidentally removed earlier.

Disease annotations do_name fix 

---

indexer/src/loaders/gene_loader.py

moved mod ids and urls into the crossReference collection with a boolean to tell whether it is a MOD id or not.

moving mod url and mod ids into crossreferences collection for a gene

---

api/src/server.py
api/src/services/helpers/search_helper.py
api/test/integration_tests/test_search.py
webapp/src/lib/searchHelpers.js

Added disease name to list of searchable fields

AGR-344  Find genes by disease name

---

indexer/src/fetch_and_save.py
indexer/src/fetch_save_index.py
indexer/src/fetch_save_test_index.py
indexer/src/load_and_index.py

This update removes the now unused fetch and index scripts.

AGR-257 Removed unused (old) fetch / index files.

---

webapp/src/containers/wordpress/index.js
webapp/src/routes.js

Hi @LucyHut Thanks a lot for working on the wordpress routes. I tried a minor fix to make it more explicit what redirect is happening. And separate out the path rewriting logic out of your Wordpress component.
Not sure if this is useful for your PR (I'm filing this PR against your feature branch). If it doesn't work, I will close it off.
#312

simplify wordpress related routing

---

webapp/src/containers/layout/menu.js
webapp/src/containers/layout/subMenu.js
webapp/src/containers/wordpress/index.js
webapp/src/routes.js

@sibyl229 --- changes are ready to be pulled in .

Agr 351 - wordpress integration

---

webapp/src/containers/genePage/style.css

Added media query in the style to fix content display.

AGR-220 : Section headings munge into content

---

webapp/src/components/orthology/orthologyTable.js

- fix ortholog score denominator
- sort orthologs by species taxonomic order, and when tie sort by score numerator
- indicate species alteration by table row shading
for testing:
http://dev.alliancegenome.org:4001/gene/WB:WBGene00000912
AGR-305

Agr 305 orthologs revision 1

---

webapp/src/components/geneOntologyRibbon/fixRibbonPlacement.js
webapp/src/components/geneOntologyRibbon/index.js
webapp/src/components/style.css
webapp/src/containers/genePage/index.js

- move ribbon 
- temp fix extra whitespace: 914d61c can be reverted when issue is fixed for the Ribbon component https://github.com/geneontology/ribbon/issues/13
AGR-367

Agr 367 Move Ribbon above

---

webapp/src/components/orthology/constants.js
webapp/src/components/orthology/orthologyTable.js

ortholog score and method bug fix

Agr 305 orthology fix score

---

webapp/src/containers/layout/socialMedia.js
webapp/src/containers/layout/topBar.js

Replaced react component "LINK"  with  "a"  for external links within the topBar and the socialMedia react  components  - Email, Facebook, twitter, and link to GitHub were not working. 
It was an easy fix.

Agr 417 - External links not working

---

webapp/src/containers/layout/socialMedia.js
webapp/src/containers/layout/topBar.js

* Replaced react component <LINK> with <a> for external links
* Replaced react component <LINK> with <a> for external links

Agr 417 - External links not working (#332)

---

api/requirements.txt
indexer/src/annotators/do_annotator.py
indexer/src/annotators/so_annotator.py

This fixes the build for gocd.

Gocd fix into Development

---

indexer/src/mods/fly.py

AGR-427 into Development

---

webapp/src/containers/genePage/index.js
webapp/src/containers/genePage/transcriptInlineViewer.js

fixed look and feels of genome widget a bit

---

indexer/src/loaders/gene_loader.py

- Reset end / start / strand if not specified.   (this was a bug)
- Only specify a single valid genome location.
https://agr-jira.atlassian.net/browse/AGR-448

hopefully fixed gene loader for AGR-448

---

webapp/package.json
webapp/src/constants.js
webapp/src/containers/layout/index.js
webapp/src/containers/layout/siteMap.js
webapp/src/containers/layout/style.css
webapp/src/containers/layout/twitterWidget.js
webapp/src/public/index.html

Added a new section to display the site map and AGR recent tweets -

Agr 406 - Added Site Map and Recent Tweets

---

indexer/src/loaders/gene_loader.py

Cherry picking Nathan's changes to dev into release branch.

Agr 448 release branch

---

api/test/functional_tests/gene_page.feature
indexer/src/loaders/aggregate_loader.py
indexer/src/loaders/disease_loader.py
indexer/src/loaders/gene_loader.py
indexer/src/loaders/test_check.py
indexer/src/mods/zfin.py

AGR-457 suppress NOT qualified disease annotations, fix link to MGI pub, added fixed ZFIN file.

Agr 456 457

---

webapp/src/containers/genePage/index.js

same change as in #343 but without commits from development
the companion PR to development is #344 (on a separate branch, to avoid "update branch" messing things up =P)

Fix ribbon header PR to release

---

indexer/src/mods/human.py
indexer/src/mods/rat.py

(cherry picked from commit 2440bdfacc38873352523b974adcbbb5e945ec82)

Merge from release branch: Update RGD file anme
